// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvHksgCBYfbJjmBUysW-1bLG2G7l30n38',
    appId: '1:67561219359:web:a7501142558c5d403b3c2a',
    messagingSenderId: '67561219359',
    projectId: 'dino-merlin',
    authDomain: 'dino-merlin.firebaseapp.com',
    storageBucket: 'dino-merlin.appspot.com',
    measurementId: 'G-L85RK6Y0QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsEu7vDlVnzDeviwfLlZOInBw2LTM5qbs',
    appId: '1:67561219359:android:d0c99440ac6bf7813b3c2a',
    messagingSenderId: '67561219359',
    projectId: 'dino-merlin',
    storageBucket: 'dino-merlin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzO09vmzb_Wg8f-Ht-FprkZ8KeKvhM6WM',
    appId: '1:67561219359:ios:0e38e8751aeaede63b3c2a',
    messagingSenderId: '67561219359',
    projectId: 'dino-merlin',
    storageBucket: 'dino-merlin.appspot.com',
    iosBundleId: 'com.example.dinoMerlin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzO09vmzb_Wg8f-Ht-FprkZ8KeKvhM6WM',
    appId: '1:67561219359:ios:0e38e8751aeaede63b3c2a',
    messagingSenderId: '67561219359',
    projectId: 'dino-merlin',
    storageBucket: 'dino-merlin.appspot.com',
    iosBundleId: 'com.example.dinoMerlin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvHksgCBYfbJjmBUysW-1bLG2G7l30n38',
    appId: '1:67561219359:web:9db328b08ecebd753b3c2a',
    messagingSenderId: '67561219359',
    projectId: 'dino-merlin',
    authDomain: 'dino-merlin.firebaseapp.com',
    storageBucket: 'dino-merlin.appspot.com',
    measurementId: 'G-6KEYW52NZ7',
  );
}
